"use server";

/**
 * Asset registration mutations. Registering or importing assets is restricted to
 * admins and asset managers. Every write is recorded through the core
 * activity-log wrapper, the human-readable tag is generated by the DB (never
 * client-side), and each new asset gets a self-hosted QR payload. Actions return
 * a serializable {@link ActionResult} so the client can surface a toast.
 */
import { revalidatePath } from "next/cache";
import { eq } from "drizzle-orm";
import { z } from "zod";

import { logActivity } from "@/core/activity-log";
import { getSession, type Session } from "@/core/auth/session";
import { db } from "@/core/db";
import { assetCategories, assets } from "@/core/db/schema";
import { ApiError, ValidationError } from "@/core/errors";
import { requireRole } from "@/core/rbac";
import { qrPayload } from "@/lib/qr";
import { assetAttributes } from "./_schema";

export type ActionResult<T = unknown> =
  | ({ ok: true } & T)
  | { ok: false; error: string };

/** Roles allowed to register/import assets. */
const REGISTRAR_ROLES = ["admin", "asset_manager"] as const;

async function withRegistrar<T>(
  fn: (session: Session) => Promise<T>,
): Promise<ActionResult<T>> {
  try {
    const session = requireRole(await getSession(), REGISTRAR_ROLES);
    const result = await fn(session);
    revalidatePath("/assets");
    return { ok: true, ...result };
  } catch (error) {
    if (error instanceof ApiError) return { ok: false, error: error.message };
    console.error("Asset action failed:", error);
    return { ok: false, error: "Something went wrong. Please try again." };
  }
}

/* -------------------------------------------------------------------------- */
/*  Field coercion                                                            */
/* -------------------------------------------------------------------------- */

/** "" / undefined → null; otherwise the trimmed string. */
const optionalText = z
  .union([z.string(), z.null(), z.undefined()])
  .transform((v) => {
    if (v === null || v === undefined) return null;
    const t = v.trim();
    return t === "" ? null : t;
  });

/** A money value: accepts "1,299.00" or "1299", stores a plain decimal string. */
const optionalCost = z
  .union([z.string(), z.number(), z.null(), z.undefined()])
  .transform((v, ctx) => {
    if (v === null || v === undefined || v === "") return null;
    const cleaned = String(v).replace(/[,\s]/g, "");
    if (!/^\d+(\.\d{1,2})?$/.test(cleaned)) {
      ctx.addIssue({ code: "custom", message: "Cost must be a number." });
      return z.NEVER;
    }
    return cleaned;
  });

/** ISO YYYY-MM-DD or null. */
const optionalDate = z
  .union([z.string(), z.null(), z.undefined()])
  .transform((v, ctx) => {
    if (v === null || v === undefined || v === "") return null;
    if (!/^\d{4}-\d{2}-\d{2}$/.test(v)) {
      ctx.addIssue({ code: "custom", message: "Date must be YYYY-MM-DD." });
      return z.NEVER;
    }
    return v;
  });

const assetInput = z.object({
  name: z.string().trim().min(1, "Asset name is required"),
  categoryId: z.coerce.number().int().positive("A category is required"),
  serialNumber: optionalText,
  acquisitionDate: optionalDate,
  acquisitionCost: optionalCost,
  condition: optionalText,
  location: optionalText,
  isBookable: z.coerce.boolean().default(false),
  photoPath: optionalText,
  /** Per-category custom field values (key → string). */
  customValues: z.record(z.string(), z.string()).default({}),
});

export type AssetInput = z.input<typeof assetInput>;

/* -------------------------------------------------------------------------- */
/*  Create a single asset                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Insert one asset. The tag is generated by the DB default (asset_tag_seq); we
 * read it back and set qr_data = "assetflow:asset:<tag>" in the same
 * transaction so the QR always encodes the real tag. Custom field values are
 * stored in the module's asset_attributes sidecar. New assets start 'available'.
 */
export async function createAsset(
  raw: AssetInput,
): Promise<ActionResult<{ id: number; tag: string }>> {
  return withRegistrar(async (session) => {
    const input = assetInput.parse(raw);

    // Guard: category must exist (FK would catch it too, but this is friendlier).
    const [category] = await db
      .select({ id: assetCategories.id })
      .from(assetCategories)
      .where(eq(assetCategories.id, input.categoryId));
    if (!category) throw new ValidationError("Selected category no longer exists.");

    const { id, tag } = await db.transaction(async (tx) => {
      // Insert with a placeholder QR, then rewrite it from the DB-generated tag.
      const [inserted] = await tx
        .insert(assets)
        .values({
          name: input.name,
          categoryId: input.categoryId,
          serialNumber: input.serialNumber,
          acquisitionDate: input.acquisitionDate,
          acquisitionCost: input.acquisitionCost,
          condition: input.condition,
          location: input.location,
          isBookable: input.isBookable,
          photoPath: input.photoPath,
          qrData: "pending",
          status: "available",
        })
        .returning();

      const [asset] = await tx
        .update(assets)
        .set({ qrData: qrPayload(inserted.tag) })
        .where(eq(assets.id, inserted.id))
        .returning();

      const cleanedValues = pruneEmpty(input.customValues);
      if (Object.keys(cleanedValues).length > 0) {
        await tx
          .insert(assetAttributes)
          .values({ assetId: asset.id, values: cleanedValues });
      }

      await logActivity(
        {
          actorId: session.userId,
          action: "asset.created",
          entityType: "asset",
          entityId: asset.id,
          after: asset,
        },
        tx,
      );

      return { id: asset.id, tag: asset.tag };
    });

    return { id, tag };
  });
}

/* -------------------------------------------------------------------------- */
/*  Bulk CSV import                                                           */
/* -------------------------------------------------------------------------- */

/** One parsed CSV row as sent from the client. All values are raw strings. */
export interface CsvAssetRow {
  name?: string;
  category?: string;
  serialNumber?: string;
  acquisitionDate?: string;
  acquisitionCost?: string;
  condition?: string;
  location?: string;
  isBookable?: string;
}

export interface ImportRowResult {
  /** 1-based row number as shown to the user. */
  row: number;
  status: "imported" | "error";
  tag?: string;
  name?: string;
  error?: string;
}

function parseBool(v: string | undefined): boolean {
  if (!v) return false;
  return ["true", "yes", "y", "1"].includes(v.trim().toLowerCase());
}

/**
 * Validate and import a batch of CSV rows. Each row is checked independently
 * (required name, a category that exists by name); valid rows are inserted with
 * an auto-generated tag + QR, invalid rows are reported with a reason. A row
 * failure never aborts the others.
 */
export async function importAssets(
  rows: CsvAssetRow[],
): Promise<
  ActionResult<{ results: ImportRowResult[]; imported: number }>
> {
  return withRegistrar(async (session) => {
    if (!Array.isArray(rows) || rows.length === 0) {
      throw new ValidationError("The CSV had no data rows.");
    }
    if (rows.length > 500) {
      throw new ValidationError("Please import 500 rows or fewer at a time.");
    }

    // Category lookup by lowercased name.
    const categories = await db
      .select({ id: assetCategories.id, name: assetCategories.name })
      .from(assetCategories);
    const categoryByName = new Map(
      categories.map((c) => [c.name.trim().toLowerCase(), c.id]),
    );

    const results: ImportRowResult[] = [];
    let imported = 0;

    for (let i = 0; i < rows.length; i++) {
      const rowNo = i + 1;
      const raw = rows[i];
      const name = (raw.name ?? "").trim();
      const categoryName = (raw.category ?? "").trim();

      if (!name) {
        results.push({ row: rowNo, status: "error", error: "Name is required." });
        continue;
      }
      if (!categoryName) {
        results.push({ row: rowNo, status: "error", error: "Category is required." });
        continue;
      }
      const categoryId = categoryByName.get(categoryName.toLowerCase());
      if (!categoryId) {
        results.push({
          row: rowNo,
          status: "error",
          name,
          error: `Unknown category "${categoryName}".`,
        });
        continue;
      }

      const parsed = assetInput.safeParse({
        name,
        categoryId,
        serialNumber: raw.serialNumber,
        acquisitionDate: raw.acquisitionDate,
        acquisitionCost: raw.acquisitionCost,
        condition: raw.condition,
        location: raw.location,
        isBookable: parseBool(raw.isBookable),
      });
      if (!parsed.success) {
        results.push({
          row: rowNo,
          status: "error",
          name,
          error: parsed.error.issues[0]?.message ?? "Invalid row.",
        });
        continue;
      }

      const input = parsed.data;
      try {
        const tag = await db.transaction(async (tx) => {
          const [inserted] = await tx
            .insert(assets)
            .values({
              name: input.name,
              categoryId: input.categoryId,
              serialNumber: input.serialNumber,
              acquisitionDate: input.acquisitionDate,
              acquisitionCost: input.acquisitionCost,
              condition: input.condition,
              location: input.location,
              isBookable: input.isBookable,
              qrData: "pending",
              status: "available",
            })
            .returning();

          const [asset] = await tx
            .update(assets)
            .set({ qrData: qrPayload(inserted.tag) })
            .where(eq(assets.id, inserted.id))
            .returning();

          await logActivity(
            {
              actorId: session.userId,
              action: "asset.imported",
              entityType: "asset",
              entityId: asset.id,
              after: asset,
            },
            tx,
          );
          return asset.tag;
        });

        imported++;
        results.push({ row: rowNo, status: "imported", tag, name });
      } catch (error) {
        console.error(`CSV import row ${rowNo} failed:`, error);
        results.push({
          row: rowNo,
          status: "error",
          name,
          error: "Could not save this row.",
        });
      }
    }

    return { results, imported };
  });
}

/* -------------------------------------------------------------------------- */
/*  Helpers                                                                   */
/* -------------------------------------------------------------------------- */

/** Drop empty/whitespace values from a custom-field map. */
function pruneEmpty(values: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(values)) {
    const t = (v ?? "").trim();
    if (t !== "") out[k] = t;
  }
  return out;
}
